In [1]:
import numpy as np
import pandas as pd

In [2]:
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
print('Shape of credits:',credits.shape)
print('Shape of movies:',movies.shape)

Shape of credits: (4803, 4)
Shape of movies: (4803, 20)

In [7]:
#Combine the two dataframes
movies_merge=pd.merge(left=movies, how='inner', right=credits, left_on='id',right_on='movie_id').drop(['movie_id'],axis=1)

In [8]:
movies_cleaned=movies_merge.drop(columns=['homepage','title_x','title_y','status','production_countries'])

In [9]:
movies_cleaned.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 18 columns):
budget                  4803 non-null int64
genres                  4803 non-null object
id                      4803 non-null int64
keywords                4803 non-null object
original_language       4803 non-null object
original_title          4803 non-null object
overview                4800 non-null object
popularity              4803 non-null float64
production_companies    4803 non-null object
release_date            4802 non-null object
revenue                 4803 non-null int64
runtime                 4801 non-null float64
spoken_languages        4803 non-null object
tagline                 3959 non-null object
vote_average            4803 non-null float64
vote_count              4803 non-null int64
cast                    4803 non-null object
crew                    4803 non-null object
dtypes: float64(3), int64(4), object(11)
memory usage: 712.9+ KB

In [11]:
# Use Calculation to get the Weighted Average
v=movies_cleaned['vote_count']
r=movies_cleaned['vote_average']
c=movies_cleaned['vote_average'].mean()
m=movies_cleaned['vote_count'].quantile(0.7)  
# m is the minimum votes required to be listed in the top 250

In [12]:
movies_cleaned['weighted_average']=((r*v)+(c*m))/(v+m)

In [13]:
movies_cleaned.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew,weighted_average
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.148013
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.807627
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.276075
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.509565
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.098319

In [14]:
movies_ranking=movies_cleaned.sort_values('weighted_average',ascending=False)
movies_ranking[['original_title','vote_count','vote_average','weighted_average','release_date','popularity']].head(20)

,original_title,vote_count,vote_average,weighted_average,release_date,popularity
1881,The Shawshank Redemption,8205,8.5,8.340775,1994-09-23,136.747729
3337,The Godfather,5893,8.4,8.192887,1972-03-14,143.659698
662,Fight Club,9413,8.3,8.171648,1999-10-15,146.757391
3232,Pulp Fiction,8428,8.3,8.157615,1994-10-08,121.463076
65,The Dark Knight,12002,8.2,8.102674,2008-07-16,187.322927
809,Forrest Gump,7927,8.2,8.056059,1994-07-06,138.133331
1818,Schindler's List,4329,8.3,8.038748,1993-11-29,104.469351
3865,Whiplash,4254,8.3,8.034695,2014-10-10,192.528841
96,Inception,13752,8.1,8.018611,2010-07-14,167.583710
1990,The Empire Strikes Back,5879,8.2,8.010426,1980-05-17,78.517830
2294,千と千尋の神隠し,3840,8.3,8.009851,2001-07-20,118.968562
95,Interstellar,10867,8.1,7.998100,2014-11-05,724.247784
2731,The Godfather: Part II,3338,8.3,7.972685,1974-12-20,105.792936
329,The Lord of the Rings: The Return of the King,8064,8.1,7.965061,2003-12-01,123.630332
2912,Star Wars,6624,8.1,7.938092,1977-05-25,126.393695
690,The Green Mile,4048,8.2,7.935440,1999-12-10,103.698022
1553,Se7en,5765,8.1,7.916176,1995-09-22,79.579532
262,The Lord of the Rings: The Fellowship of the Ring,8705,8.0,7.880632,2001-12-18,138.049577
1847,GoodFellas,3128,8.2,7.869817,1990-09-12,63.654244
2091,The Silence of the Lambs,4443,8.1,7.867805,1991-02-01,18.174804

In [15]:
movies_ranking_pop=movies_cleaned.sort_values('popularity',ascending=False)
movies_ranking_pop[['original_title','vote_count','vote_average','weighted_average','release_date','popularity']].head(20)

,original_title,vote_count,vote_average,weighted_average,release_date,popularity
546,Minions,4571,6.4,6.365286,2015-06-17,875.581305
95,Interstellar,10867,8.1,7.998100,2014-11-05,724.247784
788,Deadpool,10995,7.4,7.334360,2016-02-09,514.569956
94,Guardians of the Galaxy,9742,7.9,7.798252,2014-07-30,481.098624
127,Mad Max: Fury Road,9427,7.2,7.135687,2015-05-13,434.278564
28,Jurassic World,8662,6.5,6.474365,2015-06-09,418.708552
199,Pirates of the Caribbean: The Curse of the Bla...,6985,7.5,7.391892,2003-07-09,271.972889
82,Dawn of the Planet of the Apes,4410,7.3,7.159397,2014-06-26,243.791743
200,The Hunger Games: Mockingjay - Part 1,5584,6.6,6.552141,2014-11-18,206.227151
88,Big Hero 6,6135,7.8,7.652256,2014-10-24,203.734590
108,Terminator Genisys,3631,5.8,5.840302,2015-06-23,202.042635
26,Captain America: Civil War,7241,7.1,7.025141,2016-04-27,198.372395
3865,Whiplash,4254,8.3,8.034695,2014-10-10,192.528841
65,The Dark Knight,12002,8.2,8.102674,2008-07-16,187.322927
270,The Martian,7268,7.6,7.488387,2015-09-30,167.932870
96,Inception,13752,8.1,8.018611,2010-07-14,167.583710
124,Frozen,5295,7.3,7.180574,2013-11-27,165.125366
9,Batman v Superman: Dawn of Justice,7004,5.7,5.730040,2016-03-23,155.790452
0,Avatar,11800,7.2,7.148013,2009-12-10,150.437577
662,Fight Club,9413,8.3,8.171648,1999-10-15,146.757391

In [16]:
# Take into account both weighted_average and popularity (5-5)
# Standerdize the two columns since they are in different ranges

from sklearn.preprocessing import MinMaxScaler

sc=MinMaxScaler()
movies_scaled=sc.fit_transform(movies_cleaned[['weighted_average','popularity']])
movies_normalized=pd.DataFrame(movies_scaled,columns=['weighted_average','popularity'])
movies_normalized.head()

   weighted_average  popularity
0          0.674339    0.171815
1          0.581403    0.158846
2          0.436273    0.122635
3          0.773054    0.128272
4          0.387739    0.050169

In [17]:
movies_cleaned[['normalized_weighted_average','normalized_popularity']]=movies_normalized
movies_cleaned.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,release_date,...,runtime,spoken_languages,tagline,vote_average,vote_count,cast,crew,weighted_average,normalized_weighted_average,normalized_popularity
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.148013,0.674339,0.171815
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.807627,0.581403,0.158846
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.276075,0.436273,0.122635
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.509565,0.773054,0.128272
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.098319,0.387739,0.050169

In [20]:
movies_cleaned['score']=movies_cleaned['normalized_weighted_average']*0.5+movies_cleaned['normalized_popularity']*0.5
movies_ranking_score=movies_cleaned.sort_values(['score'],ascending=False)
movies_ranking_score=movies_ranking_score[['original_title','vote_count','vote_average','weighted_average','release_date','popularity','score']].head(20)

In [21]:
movies_ranking_score

,original_title,vote_count,vote_average,weighted_average,release_date,popularity,score
95,Interstellar,10867,8.1,7.998100,2014-11-05,724.247784,0.866801
546,Minions,4571,6.4,6.365286,2015-06-17,875.581305,0.730315
94,Guardians of the Galaxy,9742,7.9,7.798252,2014-07-30,481.098624,0.700668
788,Deadpool,10995,7.4,7.334360,2016-02-09,514.569956,0.656453
127,Mad Max: Fury Road,9427,7.2,7.135687,2015-05-13,434.278564,0.583481
1881,The Shawshank Redemption,8205,8.5,8.340775,1994-09-23,136.747729,0.578090
65,The Dark Knight,12002,8.2,8.102674,2008-07-16,187.322927,0.574466
3865,Whiplash,4254,8.3,8.034695,2014-10-10,192.528841,0.568159
3337,The Godfather,5893,8.4,8.192887,1972-03-14,143.659698,0.561848
662,Fight Club,9413,8.3,8.171648,1999-10-15,146.757391,0.560717
96,Inception,13752,8.1,8.018611,2010-07-14,167.583710,0.551718
3232,Pulp Fiction,8428,8.3,8.157615,1994-10-08,121.463076,0.544357
809,Forrest Gump,7927,8.2,8.056059,1994-07-06,138.133331,0.540013
199,Pirates of the Caribbean: The Curse of the Bla...,6985,7.5,7.391892,2003-07-09,271.972889,0.525772
2294,千と千尋の神隠し,3840,8.3,8.009851,2001-07-20,118.968562,0.522761
88,Big Hero 6,6135,7.8,7.652256,2014-10-24,203.734590,0.522349
329,The Lord of the Rings: The Return of the King,8064,8.1,7.965061,2003-12-01,123.630332,0.519308
1818,Schindler's List,4329,8.3,8.038748,1993-11-29,104.469351,0.518426
2912,Star Wars,6624,8.1,7.938092,1977-05-25,126.393695,0.517204
262,The Lord of the Rings: The Fellowship of the Ring,8705,8.0,7.880632,2001-12-18,138.049577,0.516016